// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjFmf_6ly8aAlNfXDn7NOwc4HwPu8LIn4',
    appId: '1:1027535373710:web:11818d3c3b0e43d11410df',
    messagingSenderId: '1027535373710',
    projectId: 'coffee-shop-app-b8814',
    authDomain: 'coffee-shop-app-b8814.firebaseapp.com',
    storageBucket: 'coffee-shop-app-b8814.firebasestorage.app',
    measurementId: 'G-YH9DM3N65T',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9EiGcAet0GsqaTVn5WVCCLMogbcdIoPc',
    appId: '1:753362460424:android:8236cbbec3135624db16bd',
    messagingSenderId: '753362460424',
    projectId: 'brewhaven-coffee-2026',
    storageBucket: 'brewhaven-coffee-2026.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANlagJzyat04CXkzMvW55di6aRJHVW2a4',
    appId: '1:753362460424:web:a714e30919946fbddb16bd',
    messagingSenderId: '753362460424',
    projectId: 'brewhaven-coffee-2026',
    authDomain: 'brewhaven-coffee-2026.firebaseapp.com',
    storageBucket: 'brewhaven-coffee-2026.firebasestorage.app',
  );
}
